- Release new version 0.6.0
SUSE-Enceladus/service-access-config pull request #5
Opened 2019-03-29 22:56 UTC by rjschwei

+ Move spec file to build as python3 code
  + Remove all references and conditions for SLE 11 build
  + Fix issue with Apache plugin only writing ACL to last configured file #1

2019-04-01 21:10 UTC, smarlowucf requested changes

2019-04-01 21:10 UTC, smarlowucf commented on python3-serviceAccessConfig.spec
> +BuildRequires: systemd
Match tab for consistency.

2019-04-01 21:10 UTC, smarlowucf commented on python3-serviceAccessConfig.spec
>  %doc LICENSE README.md
Move license to license macro? `%license LICENSE`

2019-04-01 21:10 UTC, smarlowucf commented on lib/serviceAccessConfig/apache.py
> +            fout = open(cfg, 'w')
Context managers FTW :wink: :

```
with open(cfg, 'w') as fout:
    fout.write(new_content)
```

2019-04-22 23:05 UTC, smarlowucf approved these changes

2019-04-23 11:40 UTC, rjschwei commented
Requested changes implemented @smarlowucf is on vacation, merging.

2019-04-23 11:40 UTC, merged